export const APPLE_FONTS = new Map<string, [appleName: string, postScriptName: string]>([
  // Figma Name                                         Apple Name                                           PostScript Name
  ["Academy Engraved LET Plain"                       , ["Academy Engraved LET Plain:1.0"                   , "AcademyEngravedLETPlain"               ]],
  ["Al Nile Regular"                                  , ["Al Nile"                                          , "AlNile"                                ]],
  ["Al Nile Bold"                                     , ["Al Nile Bold"                                     , "AlNile-Bold"                           ]],
  ["American Typewriter Regular"                      , ["American Typewriter"                              , "AmericanTypewriter"                    ]],
  ["American Typewriter Bold"                         , ["American Typewriter Bold"                         , "AmericanTypewriter-Bold"               ]],
  ["American Typewriter Condensed"                    , ["American Typewriter Condensed"                    , "AmericanTypewriter-Condensed"          ]],
  ["American Typewriter Condensed Bold"               , ["American Typewriter Condensed Bold"               , "AmericanTypewriter-CondensedBold"      ]],
  ["American Typewriter Condensed Light"              , ["American Typewriter Condensed Light"              , "AmericanTypewriter-CondensedLight"     ]],
  ["American Typewriter Light"                        , ["American Typewriter Light"                        , "AmericanTypewriter-Light"              ]],
  ["American Typewriter Semibold"                     , ["American Typewriter Semibold"                     , "AmericanTypewriter-Semibold"           ]],
  ["N/A"                                              , ["Apple Color Emoji"                                , "AppleColorEmoji"                       ]],
  ["Apple SD Gothic Neo Bold"                         , ["Apple SD Gothic Neo Bold"                         , "AppleSDGothicNeo-Bold"                 ]],
  ["Apple SD Gothic Neo Light"                        , ["Apple SD Gothic Neo Light"                        , "AppleSDGothicNeo-Light"                ]],
  ["Apple SD Gothic Neo Medium"                       , ["Apple SD Gothic Neo Medium"                       , "AppleSDGothicNeo-Medium"               ]],
  ["Apple SD Gothic Neo Regular"                      , ["Apple SD Gothic Neo Regular"                      , "AppleSDGothicNeo-Regular"              ]],
  ["Apple SD Gothic Neo SemiBold"                     , ["Apple SD Gothic Neo SemiBold"                     , "AppleSDGothicNeo-SemiBold"             ]],
  ["Apple SD Gothic Neo Thin"                         , ["Apple SD Gothic Neo Thin"                         , "AppleSDGothicNeo-Thin"                 ]],
  ["Apple SD Gothic Neo UltraLight"                   , ["Apple SD Gothic Neo UltraLight"                   , "AppleSDGothicNeo-UltraLight"           ]],
  ["Apple Symbols Regular"                            , ["Apple Symbols"                                    , "AppleSymbols"                          ]],
  ["Arial Regular"                                    , ["Arial"                                            , "ArialMT"                               ]],
  ["Arial Bold"                                       , ["Arial Bold"                                       , "Arial-BoldMT"                          ]],
  ["Arial Bold Italic"                                , ["Arial Bold Italic"                                , "Arial-BoldItalicMT"                    ]],
  ["Arial Hebrew"                                     , ["Arial Hebrew"                                     , "Arial-Hebrew"                          ]],
  ["Arial Hebrew Bold"                                , ["Arial Hebrew Bold"                                , "ArialHebrew-Bold"                      ]],
  ["Arial Hebrew Light"                               , ["Arial Hebrew Light"                               , "ArialHebrew-Light"                     ]],
  ["Arial Italic"                                     , ["Arial Italic"                                     , "Arial-ItalicMT"                        ]],
  ["Arial Rounded MT Bold Regular"                    , ["Arial Rounded MT Bold"                            , "ArialRoundedMTBold"                    ]],
  ["Avenir Black"                                     , ["Avenir Black"                                     , "Avenir-Black"                          ]],
  ["Avenir Black Oblique"                             , ["Avenir Black Oblique"                             , "Avenir-BlackOblique"                   ]],
  ["Avenir Book"                                      , ["Avenir Book"                                      , "Avenir-Book"                           ]],
  ["Avenir Book Oblique"                              , ["Avenir Book Oblique"                              , "Avenir-BookOblique"                    ]],
  ["Avenir Heavy"                                     , ["Avenir Heavy"                                     , "Avenir-Heavy"                          ]],
  ["Avenir Heavy Oblique"                             , ["Avenir Heavy Oblique"                             , "Avenir-HeavyOblique"                   ]],
  ["Avenir Light"                                     , ["Avenir Light"                                     , "Avenir-Light"                          ]],
  ["Avenir Light Oblique"                             , ["Avenir Light Oblique"                             , "Avenir-LightOblique"                   ]],
  ["Avenir Medium"                                    , ["Avenir Medium"                                    , "Avenir-Medium"                         ]],
  ["Avenir Medium Oblique"                            , ["Avenir Medium Oblique"                            , "Avenir-MediumOblique"                  ]],
  ["Avenir Next Bold"                                 , ["Avenir Next Bold"                                 , "AvenirNext-Bold"                       ]],
  ["Avenir Next Bold Italic"                          , ["Avenir Next Bold Italic"                          , "AvenirNext-BoldItalic"                 ]],
  ["Avenir Next Condensed Bold"                       , ["Avenir Next Condensed Bold"                       , "AvenirNextCondensed-Bold"              ]],
  ["Avenir Next Condensed Bold Italic"                , ["Avenir Next Condensed Bold Italic"                , "AvenirNextCondensed-BoldItalic"        ]],
  ["Avenir Next Condensed Demi Bold"                  , ["Avenir Next Condensed Demi Bold"                  , "AvenirNextCondensed-DemiBold"          ]],
  ["Avenir Next Condensed Demi Bold Italic"           , ["Avenir Next Condensed Demi Bold Italic"           , "AvenirNextCondensed-DemiBoldItalic"    ]],
  ["Avenir Next Condensed Heavy"                      , ["Avenir Next Condensed Heavy"                      , "AvenirNextCondensed-Heavy"             ]],
  ["Avenir Next Condensed Heavy Italic"               , ["Avenir Next Condensed Heavy Italic"               , "AvenirNextCondensed-HeavyItalic"       ]],
  ["Avenir Next Condensed Italic"                     , ["Avenir Next Condensed Italic"                     , "AvenirNextCondensed-Italic"            ]],
  ["Avenir Next Condensed Medium"                     , ["Avenir Next Condensed Medium"                     , "AvenirNextCondensed-Medium"            ]],
  ["Avenir Next Condensed Medium Italic"              , ["Avenir Next Condensed Medium Italic"              , "AvenirNextCondensed-MediumItalic"      ]],
  ["Avenir Next Condensed Regular"                    , ["Avenir Next Condensed Regular"                    , "AvenirNextCondensed-Regular"           ]],
  ["Avenir Next Condensed Ultra Light"                , ["Avenir Next Condensed Ultra Light"                , "AvenirNextCondensed-UltraLight"        ]],
  ["Avenir Next Condensed Ultra Light Italic"         , ["Avenir Next Condensed Ultra Light Italic"         , "AvenirNextCondensed-UltraLightItalic"  ]],
  ["Avenir Next Demi Bold"                            , ["Avenir Next Demi Bold"                            , "AvenirNext-DemiBold"                   ]],
  ["Avenir Next Demi Bold Italic"                     , ["Avenir Next Demi Bold Italic"                     , "AvenirNext-DemiBoldItalic"             ]],
  ["Avenir Next Heavy"                                , ["Avenir Next Heavy"                                , "AvenirNext-Heavy"                      ]],
  ["Avenir Next Heavy Italic"                         , ["Avenir Next Heavy Italic"                         , "AvenirNext-HeavyItalic"                ]],
  ["Avenir Next Italic"                               , ["Avenir Next Italic"                               , "AvenirNext-Italic"                     ]],
  ["Avenir Next Medium"                               , ["Avenir Next Medium"                               , "AvenirNext-Medium"                     ]],
  ["Avenir Next Medium Italic"                        , ["Avenir Next Medium Italic"                        , "AvenirNext-MediumItalic"               ]],
  ["Avenir Next Regular"                              , ["Avenir Next Regular"                              , "AvenirNext-Regular"                    ]],
  ["Avenir Next Ultra Light"                          , ["Avenir Next Ultra Light"                          , "AvenirNext-UltraLight"                 ]],
  ["Avenir Next Ultra Light Italic"                   , ["Avenir Next Ultra Light Italic"                   , "AvenirNext-UltraLightItalic"           ]],
  ["Avenir Oblique"                                   , ["Avenir Oblique"                                   , "Avenir-Oblique"                        ]],
  ["Avenir Roman"                                     , ["Avenir Roman"                                     , "Avenir-Roman"                          ]],
  ["Baskerville Regular"                              , ["Baskerville"                                      , "Baskerville"                           ]],
  ["Baskerville Bold"                                 , ["Baskerville Bold"                                 , "Baskerville-Bold"                      ]],
  ["Baskerville Bold Italic"                          , ["Baskerville Bold Italic"                          , "Baskerville-BoldItalic"                ]],
  ["Baskerville Italic"                               , ["Baskerville Italic"                               , "Baskerville-Italic"                    ]],
  ["Baskerville SemiBold"                             , ["Baskerville SemiBold"                             , "Baskerville-SemiBold"                  ]],
  ["Baskerville SemiBold Italic"                      , ["Baskerville SemiBold Italic"                      , "Baskerville-SemiBoldItalic"            ]],
  ["Bodoni 72 Bold"                                   , ["Bodoni 72 Bold"                                   , "BodoniSvtyTwoITCTT-Bold"               ]],
  ["Bodoni 72 Book"                                   , ["Bodoni 72 Book"                                   , "BodoniSvtyTwoITCTT-Book"               ]],
  ["Bodoni 72 Book Italic"                            , ["Bodoni 72 Book Italic"                            , "BodoniSvtyTwoITCTT-BookIta"            ]],
  ["Bodoni 72 Oldstyle Bold"                          , ["Bodoni 72 Oldstyle Bold"                          , "BodoniSvtyTwoOSITCTT-Bold"             ]],
  ["Bodoni 72 Oldstyle Book"                          , ["Bodoni 72 Oldstyle Book"                          , "BodoniSvtyTwoOSITCTT-Book"             ]],
  ["Bodoni 72 Oldstyle Book Italic"                   , ["Bodoni 72 Oldstyle Book Italic"                   , "BodoniSvtyTwoOSITCTT-BookIt"           ]],
  ["Bodoni 72 Smallcaps Book"                         , ["Bodoni 72 Smallcaps Book"                         , "BodoniSvtyTwoSCITCTT-Book"             ]],
  ["Bodoni Ornaments Regular"                         , ["Bodoni Ornaments"                                 , "BodoniOrnamentsITCTT"                  ]],
  ["Bradley Hand Bold"                                , ["Bradley Hand Bold"                                , "BradleyHandITCTT-Bold"                 ]],
  ["Chalkboard SE Bold"                               , ["Chalkboard SE Bold"                               , "ChalkboardSE-Bold"                     ]],
  ["Chalkboard SE Light"                              , ["Chalkboard SE Light"                              , "ChalkboardSE-Light"                    ]],
  ["Chalkboard SE Regular"                            , ["Chalkboard SE Regular"                            , "ChalkboardSE-Regular"                  ]],
  ["Chalkduster Regular"                              , ["Chalkduster"                                      , "Chalkduster"                           ]],
  ["Charter Black"                                    , ["Charter Black"                                    , "Charter-Black"                         ]],
  ["Charter Black Italic"                             , ["Charter Black Italic"                             , "Charter-BlackItalic"                   ]],
  ["Charter Bold"                                     , ["Charter Bold"                                     , "Charter-Bold"                          ]],
  ["Charter Bold Italic"                              , ["Charter Bold Italic"                              , "Charter-BoldItalic"                    ]],
  ["Charter Italic"                                   , ["Charter Italic"                                   , "Charter-Italic"                        ]],
  ["Charter Roman"                                    , ["Charter Roman"                                    , "Charter-Roman"                         ]],
  ["Cochin Regular"                                   , ["Cochin"                                           , "Cochin"                                ]],
  ["Cochin Bold"                                      , ["Cochin Bold"                                      , "Cochin-Bold"                           ]],
  ["Cochin Bold Italic"                               , ["Cochin Bold Italic"                               , "Cochin-BoldItalic"                     ]],
  ["Cochin Italic"                                    , ["Cochin Italic"                                    , "Cochin-Italic"                         ]],
  ["Copperplate Regular"                              , ["Copperplate"                                      , "Copperplate"                           ]],
  ["Copperplate Bold"                                 , ["Copperplate Bold"                                 , "Copperplate-Bold"                      ]],
  ["Copperplate Light"                                , ["Copperplate Light"                                , "Copperplate-Light"                     ]],
  ["Courier New Regular"                              , ["Courier New"                                      , "CourierNewPSMT"                        ]],
  ["Courier New Bold"                                 , ["Courier New Bold"                                 , "CourierNewPS-BoldMT"                   ]],
  ["Courier New Bold Italic"                          , ["Courier New Bold Italic"                          , "CourierNewPS-BoldItalicMT"             ]],
  ["Courier New Italic"                               , ["Courier New Italic"                               , "CourierNewPS-ItalicMT"                 ]],
  ["DIN Alternate Bold"                               , ["DIN Alternate Bold"                               , "DINAlternate-Bold"                     ]],
  ["DIN Condensed Bold"                               , ["DIN Condensed Bold"                               , "DINCondensed-Bold"                     ]],
  ["Damascus Bold"                                    , ["Damascus Bold"                                    , "DamascusBold"                          ]],
  ["Damascus Light"                                   , ["Damascus Light"                                   , "DamascusLight"                         ]],
  ["Damascus Medium"                                  , ["Damascus Medium"                                  , "DamascusMedium"                        ]],
  ["Damascus Regular"                                 , ["Damascus Regular"                                 , "Damascus"                              ]],
  ["Damascus Semi Bold"                               , ["Damascus Semi Bold"                               , "DamascusSemiBold"                      ]],
  ["Devanagari Sangam MN Regular"                     , ["Devanagari Sangam MN"                             , "DevanagariSangamMN"                    ]],
  ["Devanagari Sangam MN Bold"                        , ["Devanagari Sangam MN Bold"                        , "DevanagariSangamMN-Bold"               ]],
  ["Didot Regular"                                    , ["Didot"                                            , "Didot"                                 ]],
  ["Didot Bold"                                       , ["Didot Bold"                                       , "Didot-Bold"                            ]],
  ["Didot Italic"                                     , ["Didot Italic"                                     , "Didot-Italic"                          ]],
  ["Euphemia UCAS Regular"                            , ["Euphemia UCAS"                                    , "EuphemiaUCAS"                          ]],
  ["Euphemia UCAS Bold"                               , ["Euphemia UCAS Bold"                               , "EuphemiaUCAS-Bold"                     ]],
  ["Euphemia UCAS Italic"                             , ["Euphemia UCAS Italic"                             , "EuphemiaUCAS-Italic"                   ]],
  ["Farah Regular"                                    , ["Farah Regular"                                    , "Farah-Regular"                         ]],
  ["Futura Bold"                                      , ["Futura Bold"                                      , "Futura-Bold"                           ]],
  ["Futura Condensed ExtraBold"                       , ["Futura Condensed ExtraBold"                       , "Futura-CondensedExtraBold"             ]],
  ["Futura Condensed Medium"                          , ["Futura Condensed Medium"                          , "Futura-CondensedMedium"                ]],
  ["Futura Medium"                                    , ["Futura Medium"                                    , "Futura-Medium"                         ]],
  ["Futura Medium Italic"                             , ["Futura Medium Italic"                             , "Futura-MediumItalic"                   ]],
  ["Galvji Regular"                                   , ["Galvji"                                           , "Galvji"                                ]],
  ["Galvji Bold"                                      , ["Galvji Bold"                                      , "Galvji-Bold"                           ]],
  ["Geeza Pro Bold"                                   , ["Geeza Pro Bold"                                   , "GeezaPro-Bold"                         ]],
  ["Geeza Pro Regular"                                , ["Geeza Pro Regular"                                , "GeezaPro"                              ]],
  ["Georgia Regular"                                  , ["Georgia"                                          , "Georgia"                               ]],
  ["Georgia Bold"                                     , ["Georgia Bold"                                     , "Georgia-Bold"                          ]],
  ["Georgia Bold Italic"                              , ["Georgia Bold Italic"                              , "Georgia-BoldItalic"                    ]],
  ["Georgia Italic"                                   , ["Georgia Italic"                                   , "Georgia-Italic"                        ]],
  ["Gill Sans Regular"                                , ["Gill Sans"                                        , "GillSans"                              ]],
  ["Gill Sans Bold"                                   , ["Gill Sans Bold"                                   , "GillSans-Bold"                         ]],
  ["Gill Sans Bold Italic"                            , ["Gill Sans Bold Italic"                            , "GillSans-BoldItalic"                   ]],
  ["Gill Sans Italic"                                 , ["Gill Sans Italic"                                 , "GillSans-Italic"                       ]],
  ["Gill Sans Light"                                  , ["Gill Sans Light"                                  , "GillSans-Light"                        ]],
  ["Gill Sans Light Italic"                           , ["Gill Sans Light Italic"                           , "GillSans-LightItalic"                  ]],
  ["Gill Sans SemiBold"                               , ["Gill Sans SemiBold"                               , "GillSans-SemiBold"                     ]],
  ["Gill Sans SemiBold Italic"                        , ["Gill Sans SemiBold Italic"                        , "GillSans-SemiBoldItalic"               ]],
  ["Gill Sans UltraBold"                              , ["Gill Sans UltraBold"                              , "GillSans-UltraBold"                    ]],
  ["Grantha Sangam MN Bold"                           , ["Grantha Sangam MN Bold"                           , "GranthaSangamMN-Bold"                  ]],
  ["Grantha Sangam MN Regular"                        , ["Grantha Sangam MN Regular"                        , "GranthaSangamMN-Regular"               ]],
  ["Helvetica Regular"                                , ["Helvetica"                                        , "Helvetica"                             ]],
  ["Helvetica Bold"                                   , ["Helvetica Bold"                                   , "Helvetica-Bold"                        ]],
  ["Helvetica Bold Oblique"                           , ["Helvetica Bold Oblique"                           , "Helvetica-BoldOblique"                 ]],
  ["Helvetica Light"                                  , ["Helvetica Light"                                  , "Helvetica-Light"                       ]],
  ["Helvetica Light Oblique"                          , ["Helvetica Light Oblique"                          , "Helvetica-LightOblique"                ]],
  ["Helvetica Neue Regular"                           , ["Helvetica Neue"                                   , "HelveticaNeue"                         ]],
  ["Helvetica Neue Bold"                              , ["Helvetica Neue Bold"                              , "HelveticaNeue-Bold"                    ]],
  ["Helvetica Neue Bold Italic"                       , ["Helvetica Neue Bold Italic"                       , "HelveticaNeue-BoldItalic"              ]],
  ["Helvetica Neue Condensed Black"                   , ["Helvetica Neue Condensed Black"                   , "HelveticaNeue-CondensedBlack"          ]],
  ["Helvetica Neue Condensed Bold"                    , ["Helvetica Neue Condensed Bold"                    , "HelveticaNeue-CondensedBold"           ]],
  ["Helvetica Neue Italic"                            , ["Helvetica Neue Italic"                            , "HelveticaNeue-Italic"                  ]],
  ["Helvetica Neue Light"                             , ["Helvetica Neue Light"                             , "HelveticaNeue-Light"                   ]],
  ["Helvetica Neue Light Italic"                      , ["Helvetica Neue Light Italic"                      , "HelveticaNeue-LightItalic"             ]],
  ["Helvetica Neue Medium"                            , ["Helvetica Neue Medium"                            , "HelveticaNeue-Medium"                  ]],
  ["Helvetica Neue Medium Italic"                     , ["Helvetica Neue Medium Italic"                     , "HelveticaNeue-MediumItalic"            ]],
  ["Helvetica Neue Thin"                              , ["Helvetica Neue Thin"                              , "HelveticaNeue-Thin"                    ]],
  ["Helvetica Neue Thin Italic"                       , ["Helvetica Neue Thin Italic"                       , "HelveticaNeue-ThinItalic"              ]],
  ["Helvetica Neue UltraLight"                        , ["Helvetica Neue UltraLight"                        , "HelveticaNeue-UltraLight"              ]],
  ["Helvetica Neue UltraLight Italic"                 , ["Helvetica Neue UltraLight Italic"                 , "HelveticaNeue-UltraLightItalic"        ]],
  ["Helvetica Oblique"                                , ["Helvetica Oblique"                                , "Helvetica-Oblique"                     ]],
  ["Hiragino Maru Gothic ProN W4"                     , ["Hiragino Maru Gothic ProN W4"                     , "HiraMaruProN-W4"                       ]],
  ["Hiragino Mincho ProN W3"                          , ["Hiragino Mincho ProN W3"                          , "HiraMinProN-W3"                        ]],
  ["Hiragino Mincho ProN W6"                          , ["Hiragino Mincho ProN W6"                          , "HiraMinProN-W6"                        ]],
  ["Hiragino Sans W3"                                 , ["Hiragino Sans W3"                                 , "HiraginoSansW3"                        ]],
  ["Hiragino Sans W6"                                 , ["Hiragino Sans W6"                                 , "HiraginoSansW6"                        ]],
  ["Hiragino Sans W7"                                 , ["Hiragino Sans W7"                                 , "HiraginoSansW7"                        ]],
  ["Hoefler Text Regular"                             , ["Hoefler Text"                                     , "HoeflerText-Regular"                   ]],
  ["Hoefler Text Black"                               , ["Hoefler Text Black"                               , "HoeflerText-Black"                     ]],
  ["Hoefler Text Black Italic"                        , ["Hoefler Text Black Italic"                        , "HoeflerText-BlackItalic"               ]],
  ["Hoefler Text Italic"                              , ["Hoefler Text Italic"                              , "HoeflerText-Italic"                    ]],
  ["Impact Regular"                                   , ["Impact"                                           , "Impact"                                ]],
  ["Kailasa Bold"                                     , ["Kailasa Bold"                                     , "Kailasa-Bold"                          ]],
  ["Kailasa Regular"                                  , ["Kailasa Regular"                                  , "Kailasa"                               ]],
  ["Kefa Regular"                                     , ["Kefa Regular"                                     , "Kefa-Regular"                          ]],
  ["Khmer Sangam MN Regular"                          , ["Khmer Sangam MN"                                  , "KhmerSangamMN"                         ]],
  ["Kohinoor Bangla Regular"                          , ["Kohinoor Bangla"                                  , "KohinoorBangla-Regular"                ]],
  ["Kohinoor Bangla Light"                            , ["Kohinoor Bangla Light"                            , "KohinoorBangla-Light"                  ]],
  ["Kohinoor Bangla Semibold"                         , ["Kohinoor Bangla Semibold"                         , "KohinoorBangla-Semibold"               ]],
  ["Kohinoor Devanagari Light"                        , ["Kohinoor Devanagari Light"                        , "KohinoorDevanagari-Light"              ]],
  ["Kohinoor Devanagari Regular"                      , ["Kohinoor Devanagari Regular"                      , "KohinoorDevanagari-Regular"            ]],
  ["Kohinoor Devanagari Semibold"                     , ["Kohinoor Devanagari Semibold"                     , "KohinoorDevanagari-Semibold"           ]],
  ["Kohinoor Gujarati Bold"                           , ["Kohinoor Gujarati Bold"                           , "KohinoorGujarati-Bold"                 ]],
  ["Kohinoor Gujarati Light"                          , ["Kohinoor Gujarati Light"                          , "KohinoorGujarati-Light"                ]],
  ["Kohinoor Gujarati Regular"                        , ["Kohinoor Gujarati Regular"                        , "KohinoorGujarati-Regular"              ]],
  ["Kohinoor Telugu Regular"                          , ["Kohinoor Telugu"                                  , "KohinoorTelugu-Regular"                ]],
  ["Kohinoor Telugu Light"                            , ["Kohinoor Telugu Light"                            , "KohinoorTelugu-Light"                  ]],
  ["Kohinoor Telugu Medium"                           , ["Kohinoor Telugu Medium"                           , "KohinoorTelugu-Medium"                 ]],
  ["Lao Sangam MN Regular"                            , ["Lao Sangam MN"                                    , "LaoSangamMN"                           ]],
  ["Malayalam Sangam MN Regular"                      , ["Malayalam Sangam MN"                              , "MalayalamSangamMN"                     ]],
  ["Malayalam Sangam MN Bold"                         , ["Malayalam Sangam MN Bold"                         , "MalayalamSangamMN-Bold"                ]],
  ["Marker Felt Thin"                                 , ["Marker Felt Thin"                                 , "MarkerFelt-Thin"                       ]],
  ["Marker Felt Wide"                                 , ["Marker Felt Wide"                                 , "MarkerFelt-Wide"                       ]],
  ["Menlo Bold"                                       , ["Menlo Bold"                                       , "Menlo-Bold"                            ]],
  ["Menlo Bold Italic"                                , ["Menlo Bold Italic"                                , "Menlo-BoldItalic"                      ]],
  ["Menlo Italic"                                     , ["Menlo Italic"                                     , "Menlo-Italic"                          ]],
  ["Menlo Regular"                                    , ["Menlo Regular"                                    , "Menlo-Regular"                         ]],
  ["Mishafi Regular"                                  , ["Mishafi Regular"                                  , "DiwanMishafi"                          ]],
  ["Mukta Mahee Bold"                                 , ["MuktaMahee Bold"                                  , "MuktaMahee-Bold"                       ]],
  ["Mukta Mahee Light"                                , ["MuktaMahee Light"                                 , "MuktaMahee-Light"                      ]],
  ["Mukta Mahee Regular"                              , ["MuktaMahee Regular"                               , "MuktaMahee-Regular"                    ]],
  ["Myanmar Sangam MN Regular"                        , ["Myanmar Sangam MN"                                , "MyanmarSangamMN"                       ]],
  ["Myanmar Sangam MN Bold"                           , ["Myanmar Sangam MN Bold"                           , "MyanmarSangamMN-Bold"                  ]],
  ["Noteworthy Bold"                                  , ["Noteworthy Bold"                                  , "Noteworthy-Bold"                       ]],
  ["Noteworthy Light"                                 , ["Noteworthy Light"                                 , "Noteworthy-Light"                      ]],
  ["Noto Nastaliq Urdu Regular"                       , ["Noto Nastaliq Urdu"                               , "NotoNastaliqUrdu"                      ]],
  ["Noto Nastaliq Urdu Bold"                          , ["Noto Nastaliq Urdu Bold"                          , "NotoNastaliqUrdu-Bold"                 ]],
  ["Noto Sans Kannada Bold"                           , ["Noto Sans Kannada Bold"                           , "NotoSansKannada-Bold"                  ]],
  ["Noto Sans Kannada Light"                          , ["Noto Sans Kannada Light"                          , "NotoSansKannada-Light"                 ]],
  ["Noto Sans Kannada Regular"                        , ["Noto Sans Kannada Regular"                        , "NotoSansKannada-Regular"               ]],
  ["Noto Sans Myanmar Bold"                           , ["Noto Sans Myanmar Bold"                           , "NotoSansMyanmar-Bold"                  ]],
  ["Noto Sans Myanmar Light"                          , ["Noto Sans Myanmar Light"                          , "NotoSansMyanmar-Light"                 ]],
  ["Noto Sans Myanmar Regular"                        , ["Noto Sans Myanmar Regular"                        , "NotoSansMyanmar-Regular"               ]],
  ["Noto Sans Oriya Regular"                          , ["Noto Sans Oriya"                                  , "NotoSansOriya"                         ]],
  ["Noto Sans Oriya Bold"                             , ["Noto Sans Oriya Bold"                             , "NotoSansOriya-Bold"                    ]],
  ["Optima Bold"                                      , ["Optima Bold"                                      , "Optima-Bold"                           ]],
  ["Optima Bold Italic"                               , ["Optima Bold Italic"                               , "Optima-BoldItalic"                     ]],
  ["Optima ExtraBlack"                                , ["Optima ExtraBlack"                                , "Optima-ExtraBlack"                     ]],
  ["Optima Italic"                                    , ["Optima Italic"                                    , "Optima-Italic"                         ]],
  ["Optima Regular"                                   , ["Optima Regular"                                   , "Optima-Regular"                        ]],
  ["Palatino Regular"                                 , ["Palatino"                                         , "Palatino-Roman"                        ]],
  ["Palatino Bold"                                    , ["Palatino Bold"                                    , "Palatino-Bold"                         ]],
  ["Palatino Bold Italic"                             , ["Palatino Bold Italic"                             , "Palatino-BoldItalic"                   ]],
  ["Palatino Italic"                                  , ["Palatino Italic"                                  , "Palatino-Italic"                       ]],
  ["Papyrus Regular"                                  , ["Papyrus"                                          , "Papyrus"                               ]],
  ["Papyrus Condensed"                                , ["Papyrus Condensed"                                , "Papyrus-Condensed"                     ]],
  ["Party LET Plain"                                  , ["Party LET Plain"                                  , "PartyLETPlain"                         ]],
  ["PingFang HK Light"                                , ["PingFang HK Light"                                , "PingFangHK-Light"                      ]],
  ["PingFang HK Medium"                               , ["PingFang HK Medium"                               , "PingFangHK-Medium"                     ]],
  ["PingFang HK Regular"                              , ["PingFang HK Regular"                              , "PingFangHK-Regular"                    ]],
  ["PingFang HK Semibold"                             , ["PingFang HK Semibold"                             , "PingFangHK-Semibold"                   ]],
  ["PingFang HK Thin"                                 , ["PingFang HK Thin"                                 , "PingFangHK-Thin"                       ]],
  ["PingFang HK Ultralight"                           , ["PingFang HK Ultralight"                           , "PingFangHK-Ultralight"                 ]],
  ["PingFang SC Light"                                , ["PingFang SC Light"                                , "PingFangSC-Light"                      ]],
  ["PingFang SC Medium"                               , ["PingFang SC Medium"                               , "PingFangSC-Medium"                     ]],
  ["PingFang SC Regular"                              , ["PingFang SC Regular"                              , "PingFangSC-Regular"                    ]],
  ["PingFang SC Semibold"                             , ["PingFang SC Semibold"                             , "PingFangSC-Semibold"                   ]],
  ["PingFang SC Thin"                                 , ["PingFang SC Thin"                                 , "PingFangSC-Thin"                       ]],
  ["PingFang SC Ultralight"                           , ["PingFang SC Ultralight"                           , "PingFangSC-Ultralight"                 ]],
  ["PingFang TC Light"                                , ["PingFang TC Light"                                , "PingFangTC-Light"                      ]],
  ["PingFang TC Medium"                               , ["PingFang TC Medium"                               , "PingFangTC-Medium"                     ]],
  ["PingFang TC Regular"                              , ["PingFang TC Regular"                              , "PingFangTC-Regular"                    ]],
  ["PingFang TC Semibold"                             , ["PingFang TC Semibold"                             , "PingFangTC-Semibold"                   ]],
  ["PingFang TC Thin"                                 , ["PingFang TC Thin"                                 , "PingFangTC-Thin"                       ]],
  ["PingFang TC Ultralight"                           , ["PingFang TC Ultralight"                           , "PingFangTC-Ultralight"                 ]],
  ["Rockwell Regular"                                 , ["Rockwell"                                         , "Rockwell-Regular"                      ]],
  ["Rockwell Bold"                                    , ["Rockwell Bold"                                    , "Rockwell-Bold"                         ]],
  ["Rockwell Bold Italic"                             , ["Rockwell Bold Italic"                             , "Rockwell-BoldItalic"                   ]],
  ["Rockwell Italic"                                  , ["Rockwell Italic"                                  , "Rockwell-Italic"                       ]],
  ["STIX Two Math Regular"                            , ["STIX Two Math Regular"                            , "STIXTwoMath-Regular"                   ]],
  ["STIX Two Text Bold"                               , ["STIX Two Text Bold"                               , "STIXTwoText_Bold"                      ]],
  ["STIX Two Text Bold Italic"                        , ["STIX Two Text Bold Italic"                        , "STIXTwoText-Italic_Bold-Italic"        ]],
  ["STIX Two Text Italic"                             , ["STIX Two Text Italic"                             , "STIXTwoText-Italic"                    ]],
  ["STIX Two Text Medium Italic"                      , ["STIX Two Text Medium Italic"                      , "STIXTwoText-Italic_Medium-Italic"      ]],
  ["STIX Two Text SemiBold Italic"                    , ["STIX Two Text SemiBold Italic"                    , "STIXTwoText-Italic_SemiBold-Italic"    ]],
  ["STIX Two Text Medium"                             , ["STIX Two Text Medium"                             , "STIXTwoText_Medium"                    ]],
  ["STIX Two Text Regular"                            , ["STIX Two Text Regular"                            , "STIXTwoTextRegular"                    ]],
  ["STIX Two Text SemiBold"                           , ["STIX Two Text SemiBold"                           , "STIXTwoText_SemiBold"                  ]],
  ["Savoye LET Plain"                                 , ["Savoye LET Plain:1.0"                             , "SavoyeLetPlain"                        ]],
  ["Sinhala Sangam MN Regular"                        , ["Sinhala Sangam MN"                                , "SinhalaSangamMN"                       ]],
  ["Sinhala Sangam MN Bold"                           , ["Sinhala Sangam MN Bold"                           , "SinhalaSangamMN-Bold"                  ]],
  ["Snell Roundhand Regular"                          , ["Snell Roundhand"                                  , "SnellRoundhand"                        ]],
  ["Snell Roundhand Black"                            , ["Snell Roundhand Black"                            , "SnellRoundhand-Black"                  ]],
  ["Snell Roundhand Bold"                             , ["Snell Roundhand Bold"                             , "SnellRoundhand-Bold"                   ]],
  ["Symbol Regular"                                   , ["Symbol"                                           , "Symbol"                                ]],
  ["Tamil Sangam MN Regular"                          , ["Tamil Sangam MN"                                  , "TamilSangamMN"                         ]],
  ["Tamil Sangam MN Bold"                             , ["Tamil Sangam MN Bold"                             , "TamilSangamMN-Bold"                    ]],
  ["Thonburi Regular"                                 , ["Thonburi"                                         , "Thonburi"                              ]],
  ["Thonburi Bold"                                    , ["Thonburi Bold"                                    , "Thonburi-Bold"                         ]],
  ["Thonburi Light"                                   , ["Thonburi Light"                                   , "Thonburi-Light"                        ]],
  ["Times New Roman Regular"                          , ["Times New Roman"                                  , "TimesNewRomanPSMT"                     ]],
  ["Times New Roman Bold"                             , ["Times New Roman Bold"                             , "TimesNewRomanPS-BoldMT"                ]],
  ["Times New Roman Bold Italic"                      , ["Times New Roman Bold Italic"                      , "TimesNewRomanPS-BoldItalicMT"          ]],
  ["Times New Roman Italic"                           , ["Times New Roman Italic"                           , "TimesNewRomanPS-ItalicMT"              ]],
  ["Trebuchet MS Regular"                             , ["Trebuchet MS"                                     , "TrebuchetMS"                           ]],
  ["Trebuchet MS Bold"                                , ["Trebuchet MS Bold"                                , "TrebuchetMS-Bold"                      ]],
  ["Trebuchet MS Bold Italic"                         , ["Trebuchet MS Bold Italic"                         , "TrebuchetMS-BoldItalic"                ]],
  ["Trebuchet MS Italic"                              , ["Trebuchet MS Italic"                              , "TrebuchetMS-Italic"                    ]],
  ["Verdana Regular"                                  , ["Verdana"                                          , "Verdana"                               ]],
  ["Verdana Bold"                                     , ["Verdana Bold"                                     , "Verdana-Bold"                          ]],
  ["Verdana Bold Italic"                              , ["Verdana Bold Italic"                              , "Verdana-BoldItalic"                    ]],
  ["Verdana Italic"                                   , ["Verdana Italic"                                   , "Verdana-Italic"                        ]],
  ["Zapf Dingbats Regular"                            , ["Zapf Dingbats"                                    , "ZapfDingbats"                          ]],
  ["Zapfino Regular"                                  , ["Zapfino"                                          , "Zapfino"                               ]],
])

